### PR TITLE
Feature: Ubuntu 1804 support

### PR DESCRIPTION
**Pull request by lsh-0**
formula is very simple and builds on 18.04, but there are no guarantees it will stay simple or that it won't break on 20.04

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Uh, have to investigate the failure.

**Comment by giorgiosironi** [comment]
```
[2019-03-20T00:39:10.059Z] [54.196.243.104] out:   File "/usr/lib/python2.7/subprocess.py", line 938, in _execute_child
[2019-03-20T00:39:10.059Z] [54.196.243.104] out:     self.pid = os.fork()
[2019-03-20T00:39:10.059Z] [54.196.243.104] out: OSError: [Errno 12] Cannot allocate memory
```
We need a bigger instance?

**Comment by lsh-0** [comment]
I got that the first time too and just gave it a restart. What on earth could it be doing? I'll investigate

**Comment by lsh-0** [comment]
PR to disable the `snapd` service which idles at about 4.5% of 512MB ram : https://github.com/elifesciences/builder-base-formula/pull/216

`salt-minion` is quite the pig idling at 15% of 512MB but I'm not sure what to do about that.

`fail2ban` at 3.7%

there is a `/usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal` at about 3.4% , which may be us ... ? I suspect it's a new-ish feature from Ubuntu though. I can include it in the dead services in the linked PR

**Comment by lsh-0** [comment]
PR to add swap space: https://github.com/elifesciences/builder-private/pull/291

the t2.nano instance has ~5.6G free disk space, so no concerns there.

**Review by giorgiosironi — APPROVED** [review]

**Comment by lsh-0** [comment]
(forgot to add state to top file)

**Comment by lsh-0** [comment]
it finally got to the end of the highstate! some weird errors:
```
2019-03-26T23:24:43.918Z] [18.208.129.147] out: ----------
[2019-03-26T23:24:43.918Z] [18.208.129.147] out:           ID: autoremove-orphans
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:     Function: cmd.run
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:         Name: apt-get autoremove -y
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:       Result: False
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:      Comment: Command "apt-get autoremove -y" run
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:      Started: 23:20:45.348562
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:     Duration: 102074.235 ms
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:      Changes:   
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:               ----------
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:               pid:
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:                   6513
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:               retcode:
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:                   -9
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:               stderr:
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:               stdout:
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:                   Reading package lists...
[2019-03-26T23:24:43.919Z] [18.208.129.147] out:                   Building dependency tree...
```

and nginx not starting. investigating ...

**Comment by lsh-0** [comment]
turns out "-9" is the kernel killing processes. we had two failures before, 53 in this one. going to drop down to 16.04 to see if it stabilises

**Comment by lsh-0** [comment]
> We need a bigger instance?

I think we do.

opened a PR here that will use a t2.small during testing: https://github.com/elifesciences/builder/pull/491

if it's successful I can replace the instance size as well as the OS at the same time

**Comment by lsh-0** [comment]
just the nginx failure this time, saw this same failure a few builds ago. might be an ordering problem

**Comment by lsh-0** [comment]
fails on a adhoc standalone instance as well. Couldn't get it to fail in vagrant.

update: upon ssh'ing, nginx is indeed running. it is possibly this error: https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864

**Comment by lsh-0** [comment]
oh, `require_in` didn't behave as expected ... it was run *after* the service was running ... ffs.

**Comment by lsh-0** [comment]
second standalone instance didn't work with the hack properly ordered. I think that bug report and the output of `systemctl status nginx` misled me, so I output the contents of the `error.log` and saw this:

> 2019/04/01 04:49:24 [emerg] 8576#8576: BIO_new_file("/etc/certificates/redirects/certificate.chained.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/certificates/redirects/certificate.chained.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

investigating

**Comment by lsh-0** [comment]
I've figured it out, it was a state ordering issue after all. the redirects formula is actually doing something quite silly and I'm rectifying it through a series of commits. 

First one is application specific certificate support in builder-base: https://github.com/elifesciences/builder-base-formula/pull/219

Next are the changes in this formula that removes the redundant states.

Lastly is the builder-private changes that updates the names of the certificates: https://github.com/elifesciences/builder-private/pull/292

**Comment by lsh-0** [comment]
I think ... ~that to get all these building, that builder-private PR will need to become two.~

~1. merge builder-base
2. merge a builder-private change that duplicates the `redirects` certificates, so old names + new names (would symlinks work?) live alongside each other
3. give this build a kick~

... I need to stop thinking out loud

**Comment by lsh-0** [comment]
I'm not sure how to get these three PRs in piecemeal.

* the builder-base change is pretty benign but will begin affecting all projects immediately once merged
* a builder-private change that affects only 18.04 `redirects` is thus not possible
* this formula would depend on both of those changes in order to work for current environment as well as differently in 18.04

I don't think it's a good idea to prop up all that duplicated certificate handling code in `redirects` if we have an opportunity to scrap it all. 

I could make the builder-base changes specific to 18.04 instances only, get the `redirects` changes through and then remove it.

I `extend` those states in the `redirects` formula, but then we're sort of back to where we started with a big chunk of duplicated certificate code.

will sleep on it

**Comment by giorgiosironi** [comment]
At least `redirects` is never deployed to so it doesn't have Jenkins racing to update the formula. Will still run the daily highstate though.

**Comment by lsh-0** [comment]
ok, my plan is this:

1. merge builder-base
2. bring up a standalone s1804 redirects instance pinning the builder-private and redirects-formula PRs
3. if successful, merge builder-private and this formula PR, even though it's red in jenkins
4. upgrade redirects--prod to 18.04

update: launching with `./bldr masterless.launch:redirects,lsh1804test3,s1804,builder-private@d74302ce280c85de48af5e9dd13b33dcfd5f8519,redirects-formula@0126ca7cf32d6e86a96d906a788ffc8ad032e1f8`

**Comment by lsh-0** [comment]
hell yeah. perfect run in 5mins and 39secs: [redirects.pinned-highstate.success.txt](https://github.com/elifesciences/redirects-formula/files/3031887/redirects.pinned-highstate.success.txt)

subsequent highstates run fine as well

proceeding with rest of plan

**Pull request merged**
